# Generated by Django 5.2.8 on 2025-11-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_git_repo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='aws_access_key',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='aws_secret_key',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='gemini_model',
            field=models.CharField(choices=[('models/gemini-2.5-flash', 'Gemini 2.5 Flash (Recommended - Fast & Efficient)'), ('models/gemini-2.5-pro', 'Gemini 2.5 Pro (Most Capable)'), ('models/gemini-2.0-flash-exp', 'Gemini 2.0 Flash Experimental'), ('models/gemini-2.0-flash', 'Gemini 2.0 Flash (Stable)')], default='models/gemini-2.5-flash', help_text='Select which Gemini AI model to use for the chatbot', max_length=100),
        ),
    ]
