# Generated by Django 5.2.8 on 2025-11-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_appsettings_aws_access_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='git_repo_url',
        ),
    ]
