# Generated by Django 5.2.8 on 2025-11-21 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=100)),
                ('cloud_provider', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('remediated', 'Remediated'), ('ignored', 'Ignored')], default='active', max_length=20)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('expected_state', models.JSONField(default=dict)),
                ('actual_state', models.JSONField(default=dict)),
                ('initiated_by_user', models.CharField(blank=True, help_text='Username or IAM user who made the change', max_length=255, null=True)),
                ('initiated_by_role', models.CharField(blank=True, help_text='IAM role or service account used', max_length=255, null=True)),
                ('initiated_by_email', models.EmailField(blank=True, help_text='Email of the user who made the change', max_length=254, null=True)),
                ('change_timestamp', models.DateTimeField(blank=True, help_text='When the change was actually made', null=True)),
                ('change_method', models.CharField(blank=True, choices=[('console', 'AWS/GCP/Azure Console'), ('cli', 'Command Line Interface'), ('api', 'Direct API Call'), ('sdk', 'SDK/Boto3'), ('terraform', 'Terraform'), ('cloudformation', 'CloudFormation'), ('ansible', 'Ansible'), ('manual', 'Manual Change'), ('unknown', 'Unknown')], help_text='How the change was made', max_length=50, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, help_text='IP address from which the change was made', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request', null=True)),
                ('api_calls', models.JSONField(default=list, help_text='List of API calls that caused the drift')),
                ('change_summary', models.TextField(blank=True, help_text='Summary of what was changed', null=True)),
                ('root_cause_category', models.CharField(blank=True, choices=[('manual_change', 'Manual Change via Console/CLI'), ('automation_failure', 'Automation/IaC Failure'), ('emergency_fix', 'Emergency Hotfix'), ('testing', 'Testing/Experimentation'), ('misconfiguration', 'Misconfiguration'), ('unauthorized', 'Unauthorized Change'), ('unknown', 'Unknown')], help_text='Category of root cause', max_length=100, null=True)),
                ('root_cause_analysis', models.TextField(blank=True, help_text='Detailed analysis of why the drift occurred', null=True)),
            ],
        ),
    ]
